version: '3.8'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=sandro
    #   - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongodb:/data/db

  redis:
    image: redis

volumes:
  mongodb: